
import type { Property, Review, MessListing } from './types';

export const mockMessListings: MessListing[] = [
  {
    id: 'mess1',
    name: "Rohan's Tiffin Service",
    description: "Healthy and delicious home-cooked meals delivered to your doorstep. Specializing in North Indian cuisine.",
    distanceFromCollege: 1.2,
    foodType: 'veg',
    pricing: { monthly: 3500, perMeal: 120 },
    imageIds: ['mess-1-1'],
    averageRating: 4.8,
    reviewCount: 72,
    address: 'Hauz Khas, New Delhi',
    ownerId: 'owner1',
    dailyMenu: {
      monday: { breakfast: 'Aloo Paratha', lunch: 'Rajma Chawal', dinner: 'Shahi Paneer' },
      tuesday: { breakfast: 'Poha', lunch: 'Kadhi Pakoda', dinner: 'Mix Veg' },
      wednesday: { breakfast: 'Idli Sambhar', lunch: 'Chole Bhature', dinner: 'Dal Makhani' },
      thursday: { breakfast: 'Upma', lunch: 'Aloo Gobi', dinner: 'Paneer Butter Masala' },
      friday: { breakfast: 'Sandwich', lunch: 'Dal Fry', dinner: 'Kofta Curry' },
      saturday: { breakfast: 'Cheela', lunch: 'Special Thali', dinner: 'Chana Masala' },
      sunday: { breakfast: 'Puri Sabji', lunch: 'Special Thali', dinner: 'Paneer Lababdar' }
    }
  },
  {
    id: 'mess2',
    name: "Priya's Kitchen",
    description: "Authentic South Indian and North Indian dishes. Both veg and non-veg options available.",
    distanceFromCollege: 2.5,
    foodType: 'both',
    pricing: { monthly: 4500, quarterly: 12000, perMeal: 150 },
    imageIds: ['mess-2-1'],
    averageRating: 4.5,
    reviewCount: 55,
    address: 'Sector 125, Noida',
    ownerId: 'owner2',
    dailyMenu: {
      monday: { breakfast: 'Dosa', lunch: 'Chicken Curry', dinner: 'Egg Bhurji' },
      tuesday: { breakfast: 'Poha', lunch: 'Fish Fry', dinner: 'Aloo Matar' },
      wednesday: { breakfast: 'Idli Sambhar', lunch: 'Mutton Rogan Josh', dinner: 'Dal Makhani' },
      thursday: { breakfast: 'Upma', lunch: 'Chicken Biryani', dinner: 'Paneer Butter Masala' },
      friday: { breakfast: 'Sandwich', lunch: 'Dal Fry', dinner: 'Kofta Curry' },
      saturday: { breakfast: 'Cheela', lunch: 'Special Thali', dinner: 'Chana Masala' },
      sunday: { breakfast: 'Puri Sabji', lunch: 'Special Thali', dinner: 'Paneer Lababdar' }
    }
  },
  {
    id: 'mess3',
    name: "Campus Canteen",
    description: "Official university canteen serving a variety of snacks and meals at subsidized rates.",
    distanceFromCollege: 0.1,
    foodType: 'veg',
    pricing: { perMeal: 50 },
    imageIds: ['mess-3-1'],
    averageRating: 4.1,
    reviewCount: 150,
    address: 'IIT Delhi Campus',
    ownerId: 'owner3',
    dailyMenu: {
      monday: { breakfast: 'Samosa', lunch: 'Thali', dinner: 'Chowmein' },
      tuesday: { breakfast: 'Poha', lunch: 'Thali', dinner: 'Fried Rice' },
      wednesday: { breakfast: 'Idli Sambhar', lunch: 'Thali', dinner: 'Pasta' },
      thursday: { breakfast: 'Upma', lunch: 'Thali', dinner: 'Pizza' },
      friday: { breakfast: 'Sandwich', lunch: 'Thali', dinner: 'Burger' },
      saturday: { breakfast: 'Cheela', lunch: 'Special Thali', dinner: 'Chole Bhature' },
      sunday: { breakfast: 'Puri Sabji', lunch: 'Special Thali', dinner: 'Dosa' }
    }
  }
];


export const mockProperties: Property[] = [
  {
    id: 'prop1',
    name: 'Sharma Boys PG',
    collegeName: 'IIT Delhi',
    address: '123 Hauz Khas, New Delhi',
    rent: 8000,
    type: 'shared',
    facilities: ['Wi-Fi', 'Laundry', 'Geyser', 'Power Backup'],
    imageIds: ['property-3-1', 'property-1-2'],
    distanceFromCollege: 0.5,
    totalCapacity: 20,
    currentAvailability: 2,
    ownerContactNumber: '9876543210',
    propertyOwnerId: 'owner1',
    averageRating: 4.5,
    reviewCount: 25,
    description: 'Clean and affordable PG for boys, located at a walking distance from IIT Delhi. Includes all basic amenities.',
    messDetails: {
      available: true,
      type: 'veg',
      pricingModel: 'monthly',
      price: 3000,
      mealPlans: ['Breakfast + Dinner', 'All Meals'],
      timings: '8-10am, 1-3pm, 8-10pm',
      distanceFromRoom: 50, // 50 meters
    }
  },
  {
    id: 'prop2',
    name: 'Verma Residency',
    collegeName: 'Amity University',
    address: '456 Sector 125, Noida',
    rent: 12000,
    type: 'single',
    facilities: ['Wi-Fi', 'AC/Heater', 'Laundry', 'Power Backup', 'Parking'],
    imageIds: ['property-2-1', 'property-2-2'],
    distanceFromCollege: 1.2,
    totalCapacity: 15,
    currentAvailability: 5,
    ownerContactNumber: '9876543211',
    propertyOwnerId: 'owner2',
    averageRating: 4.2,
    reviewCount: 18,
    description: 'Premium single rooms with attached bathrooms. Fully furnished with AC and power backup, ideal for Amity students.',
    messDetails: {
      available: false,
      type: 'veg',
      pricingModel: 'included',
      mealPlans: [],
      timings: '',
      distanceFromRoom: 0
    }
  },
  {
    id: 'prop3',
    name: 'Green View Hostel',
    collegeName: 'IIT Delhi',
    address: '789 Green Park, New Delhi',
    rent: 9500,
    type: 'shared',
    facilities: ['Wi-Fi', 'Geyser', 'Laundry', 'Kitchen'],
    imageIds: ['property-1-1', 'property-3-2'],
    distanceFromCollege: 2.1,
    totalCapacity: 30,
    currentAvailability: 10,
    ownerContactNumber: '9876543212',
    propertyOwnerId: 'owner3',
    averageRating: 4.8,
    reviewCount: 48,
    description: 'A peaceful and green environment for students. Spacious shared rooms with large windows.',
     messDetails: {
      available: true,
      type: 'both',
      pricingModel: 'included',
      mealPlans: ['All Meals'],
      timings: '7:30-9:30am, 12:30-2:30pm, 7:30-9:30pm',
      distanceFromRoom: 20, // 20 meters
    }
  },
  {
    id: 'prop4',
    name: 'Gupta Student Homes',
    collegeName: 'Delhi University',
    address: '101 Kamla Nagar, New Delhi',
    rent: 7500,
    type: 'shared',
    facilities: ['Wi-Fi', 'Geyser'],
    imageIds: ['property-4-1'],
    distanceFromCollege: 0.8,
    totalCapacity: 25,
    currentAvailability: 3,
    ownerContactNumber: '9876543213',
    propertyOwnerId: 'owner4',
    averageRating: 3.9,
    reviewCount: 76,
    description: 'Budget-friendly PG in the heart of Kamla Nagar market, perfect for DU north campus students.',
    messDetails: {
      available: false,
      type: 'veg',
      pricingModel: 'included',
      mealPlans: [],
      timings: '',
      distanceFromRoom: 0
    }
  },
  {
    id: 'prop5',
    name: 'Modern Student Flats',
    collegeName: 'Amity University',
    address: '222 Sector 126, Noida',
    rent: 15000,
    type: 'studio',
    facilities: ['Wi-Fi', 'AC/Heater', 'Laundry', 'Power Backup', 'Kitchen', 'Gym', 'Parking'],
    imageIds: ['property-5-1'],
    distanceFromCollege: 2.0,
    totalCapacity: 10,
    currentAvailability: 1,
    ownerContactNumber: '9876543214',
    propertyOwnerId: 'owner5',
    averageRating: 4.7,
    reviewCount: 22,
    description: 'Luxurious studio apartments with a private kitchen and modern amenities. For students who prefer a premium living experience.',
    messDetails: {
      available: true,
      type: 'veg',
      pricingModel: 'per-meal',
      price: 100,
      mealPlans: ['On-demand'],
      timings: 'On-demand from nearby restaurant',
      distanceFromRoom: 100,
    }
  },
   {
    id: 'prop6',
    name: 'Singh Hostel',
    collegeName: 'Delhi University',
    address: '333 Hudson Lane, New Delhi',
    rent: 8500,
    type: 'shared',
    facilities: ['Wi-Fi', 'Geyser', 'Laundry'],
    imageIds: ['property-6-1'],
    distanceFromCollege: 1.5,
    totalCapacity: 40,
    currentAvailability: 8,
    ownerContactNumber: '9876543215',
    propertyOwnerId: 'owner6',
    averageRating: 4.1,
    reviewCount: 55,
    description: 'A popular choice among DU students, located on Hudson Lane. Offers a vibrant community atmosphere.',
    messDetails: {
      available: true,
      type: 'both',
      pricingModel: 'monthly',
      price: 3500,
      mealPlans: ['All Meals'],
      timings: '8-10am, 1-3pm, 8-10pm',
      distanceFromRoom: 10
    }
  },
  {
    id: 'prop7',
    name: 'The Student Pad',
    collegeName: 'IIT Delhi',
    address: '99 Adchini, New Delhi',
    rent: 11000,
    type: 'single',
    facilities: ['Wi-Fi', 'AC/Heater', 'Geyser', 'Power Backup', 'Parking'],
    imageIds: ['property-2-2', 'property-2-1'],
    distanceFromCollege: 1.8,
    totalCapacity: 10,
    currentAvailability: 3,
    ownerContactNumber: '9876543216',
    propertyOwnerId: 'owner7',
    averageRating: 4.6,
    reviewCount: 30,
    description: 'Well-furnished single rooms with modern amenities. Close to the metro station for easy commute.',
    messDetails: {
      available: false,
      type: 'veg',
      pricingModel: 'included',
      mealPlans: [],
      timings: '',
      distanceFromRoom: 0
    }
  },
  {
    id: 'prop8',
    name: 'Acharya Nivas',
    collegeName: 'JNU',
    address: '12 Munirka Vihar, New Delhi',
    rent: 6500,
    type: 'shared',
    facilities: ['Wi-Fi', 'Geyser'],
    imageIds: ['property-1-1'],
    distanceFromCollege: 1.0,
    totalCapacity: 50,
    currentAvailability: 15,
    ownerContactNumber: '9876543217',
    propertyOwnerId: 'owner8',
    averageRating: 3.8,
    reviewCount: 95,
    description: 'A large, no-frills hostel for students on a tight budget. Located in a student-centric area.',
    messDetails: {
      available: true,
      type: 'veg',
      pricingModel: 'monthly',
      price: 2500,
      mealPlans: ['Breakfast + Dinner'],
      timings: '8-10am, 8-10pm',
      distanceFromRoom: 0
    }
  },
  {
    id: 'prop9',
    name: 'Galaxy Apartments',
    collegeName: 'Amity University',
    address: '77 Sector 128, Noida',
    rent: 18000,
    type: 'studio',
    facilities: ['Wi-Fi', 'AC/Heater', 'Laundry', 'Power Backup', 'Kitchen', 'Gym', 'Parking', 'Pool'],
    imageIds: ['property-5-1', 'property-3-2'],
    distanceFromCollege: 3.5,
    totalCapacity: 20,
    currentAvailability: 7,
    ownerContactNumber: '9876543218',
    propertyOwnerId: 'owner9',
    averageRating: 4.9,
    reviewCount: 42,
    description: 'Luxury studio apartments with a swimming pool and gym. Experience the best-in-class living experience.',
    messDetails: {
      available: true,
      type: 'both',
      pricingModel: 'per-meal',
      price: 150,
      mealPlans: ['On-demand'],
      timings: '24x7 Cafe',
      distanceFromRoom: 200
    }
  }
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    propertyId: 'prop1',
    studentId: 'stud1',
    studentName: 'Rohan Sharma',
    rating: 5,
    comment: 'Great place, very close to college. The owner is very helpful.',
    createdAt: '2023-08-15T10:00:00Z',
  },
  {
    id: 'rev2',
    propertyId: 'prop1',
    studentId: 'stud2',
    studentName: 'Priya Singh',
    rating: 4,
    comment: 'Good value for money. The rooms are clean and well-maintained.',
    createdAt: '2023-09-01T14:30:00Z',
  },
  {
    id: 'rev3',
    propertyId: 'prop2',
    studentId: 'stud3',
    studentName: 'Ankit Kumar',
    rating: 4,
    comment: 'The AC is a lifesaver in the summer. A bit expensive, but the quality is worth it.',
    createdAt: '2023-08-20T11:00:00Z',
  },
  {
    id: 'rev4',
    propertyId: 'prop3',
    studentId: 'stud4',
    studentName: 'Sneha Gupta',
    rating: 5,
    comment: 'I love the peaceful atmosphere here. It feels like home.',
    createdAt: '2023-09-05T18:00:00Z',
  },
  {
    id: 'rev5',
    propertyId: 'prop7',
    studentId: 'stud5',
    studentName: 'Vikram Batra',
    rating: 5,
    comment: 'Perfect for serious students. Quiet and clean.',
    createdAt: '2023-10-10T12:00:00Z',
  },
  {
    id: 'rev6',
    propertyId: 'prop9',
    studentId: 'stud6',
    studentName: 'Aisha Kapoor',
    rating: 5,
    comment: 'The pool is amazing! Totally worth the price.',
    createdAt: '2023-10-12T16:45:00Z',
  },
];
